name: ci

on:
  push:
    branches:
      - "master"
    # paths:
      # - '!.github/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
          dir_names: "true"
          
      - name: List with all changed files
        id: step1
        run: |
          echo "value=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

      # - name: PWD
      #   run: |
      #     pwd && ls -la && cat alpine/Dockerfile

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
        file: ${{fromJson(needs.setup.outputs.output1)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: grep and sed TAG
        run: |
          value=`grep 'TAG' ${{ matrix.file }}/Dockerfile | sed 's/.*=//'`
          echo "tag=$value" >> $GITHUB_ENV

      - name: echo tag
        run: |
          echo "${{ env.tag }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v3 
        with:
          # context: .          
          file: /${{ matrix.file }}/Dockerfile
          push: true
          tags: |
            sakup/${{ matrix.file }}:${{ env.tag }}
            sakup/${{ matrix.file }}:latest