name: ci

on:
  push:
    branches:
      - "master"
    # paths:
    #   - '!.github/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v34
      #   with:
      #     json: "true"

      - name: Get directories
        id: directories
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
          dir_names: "true"
          
      - name: List with all changed files
        id: step1
        run: |
          echo "value=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

      - name: List directories
        run: |
          echo ${{ steps.directories.outputs.all_changed_files }} 




  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
        version: [10, 12, 14]
      # output1:
      #   file: ${{fromJson(needs.setup.outputs.output1)}}

    steps:
      - name: List with all changed files
        run: |
          echo ${{ needs.setup.outputs.output1 }}

      - name: List from matrix
        run: |
          echo ${{ matrix.version }}

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
        
      # - name: Build and push
      #   uses: docker/build-push-action@v3 
      #   if: ${{ matrix.file }} != '.github/workflows/main.yml'
      #   with:
      #     context: .          
      #     file: ${{ matrix.file }}
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:latest

      # - name: List all changed files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done