name: ci

on:
  push:
    branches:
      - "master"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: matrix
        uses: tj-actions/changed-files@v34
        #with:
          # dir_names: "true"
          #json: "true"
    
      - name: List json with all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} 

      - name: List matirx
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }} 

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.changed-files)}}
          
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        if: ${{ matrix.value }} != '.github/workflows/main.yml'
        with:
          context: .          
          file: ${{ matrix.value }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine:latest
      # - name: List all changed files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done