name: ci

on:
  push:
    branches:
      - "master"
    # paths:
      # - '!.github/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
          dir_names: "true"
          
      - name: List with all changed files
        id: step1
        run: |
          echo "value=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_OUTPUT

      # - name: PWD
      #   run: |
      #     pwd && ls -la && cat alpine/Dockerfile

  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
       matrix:
        file: ${{fromJson(needs.setup.outputs.output1)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CAT with grep and sed
        id: grep
        run: |
          echo cat ${{ matrix.file }}/Dockerfile | grep 'TAG' | sed 's/.*=//' >> $GITHUB_OUTPUT

      # - name: echo cat
      #   run: |
      #     echo "value = " >> $GITHUB_OUTPUT

      # - name: Read file contents
      #   id: read_file
      #   uses: andstor/file-reader-action@v1
      #   with:
      #     path: "${{ matrix.file }}/Dockerfile"

      # - name: File contents
      #   run: echo "${ steps.read_file.outputs.contents }"


      # - name: Get tag for image
      #   id: tag
      #   run: |
      #     echo "value = ${ cat ${{ matrix.file }}/Dockerfile | grep 'TAG' | sed 's/.*=//'}" >> $GITHUB_OUTPUT

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
        
      # - name: Build and push
      #   uses: docker/build-push-action@v3 
      #   with:
      #     # context: .          
      #     file: /${{ matrix.file }}/Dockerfile
      #     push: true
      #     tags: |
      #       sakup/${{ matrix.file }}:${{ steps.tag.outputs.value }}
      #       sakup/${{ matrix.file }}:latest